### ISSUE TITLE
Une petite amélioration du Readme

### ISSUE THREAD

**Issue by borisagbo** [ln-dev7/AppMeteo#1]
Salut et très bon taff,

Avant ma demande j'aimerais d'abord s'avoir si on peut contribuer?

- Ma demande : Une petite amélioration du readme pour permettre peut être de contribuer ( dans mon cas) ou donner plus d'infomations sur les technologies et le setup serait peut être très interressant je pense bien.

merci beaucoup

**Comment by ln-dev7** [comment]
Oui oui c'est Open Source tout le monde peut contribuer
Pour le redame je vais mettre à jour

**Comment by ln-dev7** [comment]
Dans 1h je vais update

**Comment by borisagbo** [comment]
Merci
